# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 952a3085ccab4fde0a8c14d33c1bf34601e8484fb7c523d082b587b1019a0f051fe13206942768de5219d4b0d2e0757b71d3294b4c92b6ce2f7c3d1665914f0a

test:
  secret_key_base: 514fb7bfbb42a241511b1a6fe9e5e9167daf266a5103f1357b9dd0d9bd9987f55879836bdb39dec9e85fff53dcf79c8be6edbccc0e2910a1e85c5070e43ce99d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
