# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dd2c5e1a6589c82a6e6adf505866eb191a4b457774416115efd11a609b32d17e0c5e028cbbeeb2f7557d96dd8c3717bcdb15f066d9ba4944b005581e1b7aef56

test:
  secret_key_base: 5e7e7740f3492b7ab18afb9c6cbe767ffb0a01f0f71b521382d78ea8b13abb2870566cb996aca37d222c7acebc292ae9923a11cbb23eb5ee8419cbcbcb5a95a1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
